### ISSUE TITLE
Day chart is inaccurate if user tweets too often

### ISSUE THREAD

**Issue by SteinarVP** [vladim0105/Twitter-Analyzer#12]
![image](https://user-images.githubusercontent.com/5860460/68082210-ca860700-fe54-11e9-9455-9d91e5e709f3.png)
Default fetch is 50 tweets. Trump tweets more than 50 tweets every week, leading to gaps of zero data. Should be altered to instead show that data is lacking or replace x axis with specific dates?

**Comment by vladim0105** [comment]
The dev version only does 50 tweets due to rate limitations. The built and deployed version does 200 tweets.
